/* Single-binary entry point: open the VM and run the embedded app.
 *
 * app.rb is compiled to the C array `app[]` (see mrbgem.rake) and linked in, so
 * no script file is read at runtime. The Apple Intelligence binding is
 * statically linked, so this is a self-contained binary. The run path mirrors
 * picoruby-bin-r2p2: read the embedded irep and run it as a task. */
#include "picoruby.h"
#include "mruby_compiler.h"
#include <stdio.h>
#include <stdint.h>

#ifndef HEAP_SIZE
#define HEAP_SIZE (1024 * 6400 - 1)
#endif
static uint8_t vm_heap[HEAP_SIZE];

/* The runtime references this global VM handle (so does picorb_vm_init). */
mrb_state *global_mrb = NULL;

/* Bytecode of app.rb, generated by mrbc into app.c. */
extern const uint8_t app[];

int
main(int argc, char **argv)
{
  mrb_state *vm = NULL;
  picorb_vm_init();          /* opens the VM and runs gem inits */

  mrc_irep *irep = mrb_read_irep(vm, app);
  mrc_ccontext *cc = mrc_ccontext_new(vm);
  mrb_value name = mrb_str_new_cstr(vm, "app");
  mrb_value task = mrc_create_task(cc, irep, name, mrb_nil_value(),
                                   mrb_obj_value(vm->top_self));
  if (mrb_nil_p(task)) {
    fprintf(stderr, "failed to create task for embedded app\n");
    return 1;
  }
  mrb_task_run(vm);

  /* picoruby's own runner leaves the VM open at exit (see picoruby.c cleanup);
   * the process is exiting anyway, so we do the same and skip mrb_close. */
  return 0;
}
